# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require "open-uri"


puts "Cleaning database"
JamSession.destroy_all
User.destroy_all
Instrument.destroy_all
UserInstrument.destroy_all
Request.destroy_all
Post.destroy_all
JamSessionInstrument.destroy_all


puts 'Creating 8 fake users...'
file1 = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598622297/n8xr08qf99exurskmo58chisatl7.jpg")
user1 = User.create(first_name: "Laura", last_name: "Van Nieuwland", phone_number: "0686166366", email: "lauravannieuwland@gmail.com", password: "123456" )
user1.profile_image.attach(io: file1, filename: "user1.png", content_type: 'image/png')

file2 = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598629211/nv7mj85q759mx44oaelgejupd35a.jpg")
user2 = User.create(first_name: "Raquel", last_name: "Tessarollo",
phone_number: "0655443567", email: "tessarollo.raquel@gmail.com", password: "123456")
user2.profile_image.attach(io:file2, filename:"user2.png", content_type: 'image/png')

file3 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599660197/Profile%20pics/emmanuel_macron")
user3 = User.create(first_name: "Emmanuel", last_name: "Macron",
phone_number: "+33655443567", email: "emmanuelmacron@gmail.com", password: "123456")
user3.profile_image.attach(io:file3, filename:"user3.png", content_type: 'image/png')

file4 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599660106/Profile%20pics/angela_merkel")
user4 = User.create(first_name: "Angela", last_name: "Merkel",
phone_number: "+49655443567", email: "angelamerkel@gmail.com", password: "123456")
user4.profile_image.attach(io:file4, filename:"user4.png", content_type: 'image/png')

file5 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599660058/Profile%20pics/willem_alexander")
user5 = User.create(first_name: "Willem", last_name: "Alexander",
phone_number: "+31655443567", email: "willemalexander@gmail.com", password: "123456")
user5.profile_image.attach(io:file5, filename:"user5.png", content_type: 'image/png')

file6 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599659978/Profile%20pics/kim_jong_un")
user6 = User.create(first_name: "Kim", last_name: "Jong Un",
phone_number: "+85655443567", email: "kimjongun@gmail.com", password: "123456")
user6.profile_image.attach(io:file6, filename:"user6.png", content_type: 'image/png')

file7 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599659784/Profile%20pics/trump")
user7 = User.create(first_name: "Donald", last_name: "Trump",
phone_number: "+85655443567", email: "donaldduckytrump@gmail.com", password: "123456")
user6.profile_image.attach(io:file7, filename:"user7.png", content_type: 'image/png')

file8 = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599659704/Profile%20pics/barack")
user8 = User.create(first_name: "Barack", last_name: "Obahma",
phone_number: "+85655443567", email: "barackieeeebama@gmail.com", password: "123456")
user8.profile_image.attach(io:file8, filename:"user8.png", content_type: 'image/png')


puts 'Creating instrument list...'
instrument1 = Instrument.create(instrument_type: "Guitar")
instrument2 = Instrument.create(instrument_type: "Bass Guitar")
instrument3 = Instrument.create(instrument_type: "Drums")
instrument4 = Instrument.create(instrument_type: "Violin")
instrument5 = Instrument.create(instrument_type: "Piano")
instrument6 = Instrument.create(instrument_type: "Saxophone")
instrument7 = Instrument.create(instrument_type: "Flute")
instrument8 = Instrument.create(instrument_type: "Cello")
instrument9 = Instrument.create(instrument_type: "Clarinet")
instrument10 = Instrument.create(instrument_type: "Trumpet")
instrument11 = Instrument.create(instrument_type: "Microphone")
instrument12 = Instrument.create(instrument_type: "Harp")
instrument13 = Instrument.create(instrument_type: "Banjo")
instrument14 = Instrument.create(instrument_type: "Percussion")

puts 'Creating 25 fake jamsessions... (4 per user)'
filex = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598622105/wvuec8c3rgvtwtq4spcuvgehz50t.jpg")
jamsession1  = JamSession.create(title: "Music Westerpark", starts_at: "2020-10-08 18:00:00 UTC", ends_at: "2020-10-08 20:00",
location: "Heisteeg 7 Amsterdam", user: user1, max_capacity: 20, status: "not fully booked", description: "Wild jamsession in Westerpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession1.image.attach(io:filex, filename:"jamsession1.png", content_type: 'image/png')

filey = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598518874/eletric_guitar_elpgtc.jpg")
jamsession2  = JamSession.create(title: "Music Vondelpark", starts_at: "2020-11-09 19:00 UTC", ends_at: "2020-11-09 23:59 UTC",
location: "Muntplein 3 Amsterdam", user: user1, max_capacity: 10, status: "not fully booked", description: "Wild jamsession in Vondelpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession2.image.attach(io:filey, filename:"jamsession2.png", content_type: 'image/png')

filez = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598518875/trombone_amrr9u.jpg")
jamsession3  = JamSession.create(title: "Jamsession my place", starts_at: "2020-10-12  19:00 UTC", ends_at: "2020-10-12  22:00 UTC",
location: "Espakker 23 Teteringen", user: user1, max_capacity: 5, status: "fully booked", description: "Wild jamsession in Beatrixpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession3.image.attach(io:filez, filename:"jamsession3.png", content_type: 'image/png')

filed = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1598518876/banjo_lljlgl.jpg")
jamsession4  = JamSession.create(title: "Piano concert", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Nieuwstraat 20 Breda", user: user1, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession4.image.attach(io:filed, filename:"jamsession4.png", content_type: 'image/png')

filea = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1599661943/jamsessions/image_jamsession_22.jpg")
jamsession5  = JamSession.create(title: "Guitar get together", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "'t Hol 1 Amsterdam", user: user2, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession5.image.attach(io:filea, filename:"jamsession4.png", content_type: 'image/png')

fileb = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1599661943/jamsessions/image_jamsession_23.jpg")
jamsession6  = JamSession.create(title: "Jamsession at the water", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Spuistraat 1 Amsterdam", user: user2, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession6.image.attach(io:fileb, filename:"jamsession4.png", content_type: 'image/png')

filec = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1599661943/jamsessions/image_jamsession_24.jpg")
jamsession7  = JamSession.create(title: "Cozy Jam Session", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Smak­steeg 5 Amsterdam", user: user2, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession7.image.attach(io:filec, filename:"jamsession4.png", content_type: 'image/png')

filef = URI.open("https://res.cloudinary.com/dexfami2g/image/upload/v1599661942/jamsessions/image_jamsession_25.jpg")
jamsession8  = JamSession.create(title: "Small session", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Singel 210 Amsterdam", user: user2, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession8.image.attach(io:filef, filename:"jamsession4.png", content_type: 'image/png')

fileg = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661930/jamsessions/image_jamsession_15")
jamsession9  = JamSession.create(title: "Big get together", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Taksteeg 1 Amsterdam", user: user4, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession9.image.attach(io:fileg, filename:"jamsession4.png", content_type: 'image/png')

fileh = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661919/jamsessions/image_jamsession_13")
jamsession10  = JamSession.create(title: "Come play with us!", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Nes 4 Amsterdam", user: user4, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession10.image.attach(io:fileh, filename:"jamsession4.png", content_type: 'image/png')

filei = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661907/jamsessions/image_jamsession_14")
jamsession11  = JamSession.create(title: "Jam with us", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Rokin 64 Amsterdam", user: user4, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession11.image.attach(io:filei, filename:"jamsession4.png", content_type: 'image/png')

filej = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661890/jamsessions/image_jamsession_18")
jamsession12  = JamSession.create(title: "Guitar lovers", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Nieuwendijk 20 Amsterdam", user: user4, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession12.image.attach(io:filej, filename:"jamsession4.png", content_type: 'image/png')

filek = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661879/jamsessions/image_jamsession_16")
jamsession13  = JamSession.create(title: "Make some noise", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Aalststraat 2 Breda", user: user5, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession13.image.attach(io:filek, filename:"jamsession4.png", content_type: 'image/png')

filel = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661864/jamsessions/image_jamsession_17")
jamsession14  = JamSession.create(title: "Classical Harmony", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Abeelstraat 6 Breda", user: user5, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession14.image.attach(io:filel, filename:"jamsession4.png", content_type: 'image/png')

filem = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661856/jamsessions/image_jamsession_9")
jamsession15 = JamSession.create(title: "Radio Record", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Achterom 2 Breda", user: user5, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession15.image.attach(io:filem, filename:"jamsession4.png", content_type: 'image/png')

fileo = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661847/jamsessions/image_jamsession_10")
jamsession16 = JamSession.create(title: "Even if it rains...", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Achtervang 5 Breda", user: user5, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession16.image.attach(io:fileo, filename:"jamsession4.png", content_type: 'image/png')

filep = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661837/jamsessions/image_jamsession_11")
jamsession17  = JamSession.create(title: "Summer Jam Session", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Baronielaan 88 Breda", user: user6, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession17.image.attach(io:filep, filename:"jamsession4.png", content_type: 'image/png')

fileq = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661827/jamsessions/image_jamsession_8")
jamsession18  = JamSession.create(title: "The X factor", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Bergschot 20 Breda", user: user6, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession18.image.attach(io:fileq, filename:"jamsession4.png", content_type: 'image/png')

filer = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661820/jamsessions/image_jamsession_12")
jamsession19 = JamSession.create(title: "Idols Jam Session", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Johansberg 1 Breda", user: user6, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession19.image.attach(io:filer, filename:"jamsession4.png", content_type: 'image/png')

files = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661732/jamsessions/image_jamsession_1")
jamsession20 = JamSession.create(title: "We rock!!!", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Jorisstraat 1 Breda", user: user6, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession20.image.attach(io:files, filename:"jamsession4.png", content_type: 'image/png')

filet = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661714/jamsessions/image_jamsession_2")
jamsession21 = JamSession.create(title: "Meet the rockers", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Bierstraat 1 Rotterdam", user: user8, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession21.image.attach(io:filet, filename:"jamsession4.png", content_type: 'image/png')

fileu = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661696/jamsessions/image_jamsession_3")
jamsession22  = JamSession.create(title: "Drum lovers", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Blaak 1 Rotterdam", user: user8, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession22.image.attach(io:fileu, filename:"jamsession4.png", content_type: 'image/png')

filev = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661674/jamsessions/image_jamsession_4")
jamsession23  = JamSession.create(title: "Only classics", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Rederijstraat 2 Rotterdam", user: user8, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession23.image.attach(io:filev, filename:"jamsession4.png", content_type: 'image/png')

filew = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661655/jamsessions/image_jamsession_5")
jamsession24  = JamSession.create(title: "Only pop", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Koningsdam 1 Rotterdam", user: user8, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession24.image.attach(io:filew, filename:"jamsession4.png", content_type: 'image/png')

fileaa = URI.open("https://res.cloudinary.com/dexfami2g/raw/upload/v1599661642/jamsessions/image_jamsession_6")
jamsession25 = JamSession.create(title: "Singers welcome", starts_at: "2020-12-31  11:00 UTC", ends_at: "2021-01-01  12:00 UTC",
location: "Leuvehoofd 1 Rotterdam", user: user3, max_capacity: 18, status: "not fully booked", description: "Wild jamsession in Rembrantpark, everybody is invited, come guys, it will be awesome!", lat: "", lng: "")
jamsession25.image.attach(io:fileaa, filename:"jamsession4.png", content_type: 'image/png')


puts "Creating 2 UserInstruments per user"
UserInstrument.create(skill_level: "5", user: user1, instrument: instrument1)
UserInstrument.create(skill_level: "4", user: user1, instrument: instrument2)
UserInstrument.create(skill_level: "3", user: user2, instrument: instrument3)
UserInstrument.create(skill_level: "2", user: user2, instrument: instrument4)
UserInstrument.create(skill_level: "5", user: user3, instrument: instrument5)
UserInstrument.create(skill_level: "4", user: user3, instrument: instrument6)
UserInstrument.create(skill_level: "3", user: user4, instrument: instrument7)
UserInstrument.create(skill_level: "2", user: user4, instrument: instrument8)
UserInstrument.create(skill_level: "5", user: user5, instrument: instrument9)
UserInstrument.create(skill_level: "4", user: user5, instrument: instrument10)
UserInstrument.create(skill_level: "3", user: user6, instrument: instrument11)
UserInstrument.create(skill_level: "2", user: user6, instrument: instrument12)
UserInstrument.create(skill_level: "5", user: user7, instrument: instrument13)
UserInstrument.create(skill_level: "4", user: user7, instrument: instrument14)
UserInstrument.create(skill_level: "3", user: user8, instrument: instrument1)
UserInstrument.create(skill_level: "2", user: user8, instrument: instrument2)

puts "Creating 2 JamSessionInstruments per Jam Session"
JamSessionInstrument.create(instrument: instrument1, jam_session: jamsession1)
JamSessionInstrument.create(instrument: instrument2, jam_session: jamsession2)
JamSessionInstrument.create(instrument: instrument3, jam_session: jamsession3)
JamSessionInstrument.create(instrument: instrument4, jam_session: jamsession4)
JamSessionInstrument.create(instrument: instrument5, jam_session: jamsession5)
JamSessionInstrument.create(instrument: instrument6, jam_session: jamsession6)
JamSessionInstrument.create(instrument: instrument7, jam_session: jamsession7)
JamSessionInstrument.create(instrument: instrument8, jam_session: jamsession8)
JamSessionInstrument.create(instrument: instrument9, jam_session: jamsession9)
JamSessionInstrument.create(instrument: instrument10, jam_session: jamsession10)
JamSessionInstrument.create(instrument: instrument11, jam_session: jamsession11)
JamSessionInstrument.create(instrument: instrument12, jam_session: jamsession12)
JamSessionInstrument.create(instrument: instrument13, jam_session: jamsession13)
JamSessionInstrument.create(instrument: instrument14, jam_session: jamsession14)
JamSessionInstrument.create(instrument: instrument4, jam_session: jamsession15)
JamSessionInstrument.create(instrument: instrument5, jam_session: jamsession16)
JamSessionInstrument.create(instrument: instrument7, jam_session: jamsession17)
JamSessionInstrument.create(instrument: instrument8, jam_session: jamsession18)
JamSessionInstrument.create(instrument: instrument9, jam_session: jamsession19)
JamSessionInstrument.create(instrument: instrument10, jam_session: jamsession20)
JamSessionInstrument.create(instrument: instrument11, jam_session: jamsession21)
JamSessionInstrument.create(instrument: instrument12, jam_session: jamsession22)
JamSessionInstrument.create(instrument: instrument13, jam_session: jamsession23)
JamSessionInstrument.create(instrument: instrument14, jam_session: jamsession24)
JamSessionInstrument.create(instrument: instrument14, jam_session: jamsession25)
JamSessionInstrument.create(instrument: instrument2, jam_session: jamsession1)
JamSessionInstrument.create(instrument: instrument3, jam_session: jamsession2)
JamSessionInstrument.create(instrument: instrument4, jam_session: jamsession3)
JamSessionInstrument.create(instrument: instrument5, jam_session: jamsession4)
JamSessionInstrument.create(instrument: instrument6, jam_session: jamsession5)
JamSessionInstrument.create(instrument: instrument7, jam_session: jamsession6)
JamSessionInstrument.create(instrument: instrument8, jam_session: jamsession7)
JamSessionInstrument.create(instrument: instrument9, jam_session: jamsession8)
JamSessionInstrument.create(instrument: instrument10, jam_session: jamsession9)
JamSessionInstrument.create(instrument: instrument11, jam_session: jamsession10)
JamSessionInstrument.create(instrument: instrument12, jam_session: jamsession11)
JamSessionInstrument.create(instrument: instrument13, jam_session: jamsession12)
JamSessionInstrument.create(instrument: instrument14, jam_session: jamsession13)
JamSessionInstrument.create(instrument: instrument1, jam_session: jamsession14)
JamSessionInstrument.create(instrument: instrument2, jam_session: jamsession15)
JamSessionInstrument.create(instrument: instrument3, jam_session: jamsession16)
JamSessionInstrument.create(instrument: instrument4, jam_session: jamsession17)
JamSessionInstrument.create(instrument: instrument5, jam_session: jamsession18)
JamSessionInstrument.create(instrument: instrument6, jam_session: jamsession19)
JamSessionInstrument.create(instrument: instrument7, jam_session: jamsession20)
JamSessionInstrument.create(instrument: instrument9, jam_session: jamsession21)
JamSessionInstrument.create(instrument: instrument9, jam_session: jamsession22)
JamSessionInstrument.create(instrument: instrument10, jam_session: jamsession23)
JamSessionInstrument.create(instrument: instrument11, jam_session: jamsession24)
JamSessionInstrument.create(instrument: instrument12, jam_session: jamsession25)


puts "Creating 7 requests per jamsession"

Request.create(status: "pending", jam_session: jamsession1, user: user2)
Request.create(status: "pending", jam_session: jamsession1, user: user4)
Request.create(status: "pending", jam_session: jamsession1, user: user5)
Request.create(status: "pending", jam_session: jamsession1, user: user6)
Request.create(status: "pending", jam_session: jamsession1, user: user7)
Request.create(status: "pending", jam_session: jamsession1, user: user7)
Request.create(status: "pending", jam_session: jamsession2, user: user2)
Request.create(status: "pending", jam_session: jamsession2, user: user4)
Request.create(status: "pending", jam_session: jamsession2, user: user5)
Request.create(status: "pending", jam_session: jamsession2, user: user6)
Request.create(status: "pending", jam_session: jamsession2, user: user7)
Request.create(status: "pending", jam_session: jamsession2, user: user7)
Request.create(status: "pending", jam_session: jamsession3, user: user2)
Request.create(status: "pending", jam_session: jamsession3, user: user4)
Request.create(status: "pending", jam_session: jamsession3, user: user5)
Request.create(status: "pending", jam_session: jamsession3, user: user6)
Request.create(status: "pending", jam_session: jamsession3, user: user7)
Request.create(status: "pending", jam_session: jamsession3, user: user7)
Request.create(status: "pending", jam_session: jamsession4, user: user2)
Request.create(status: "pending", jam_session: jamsession4, user: user4)
Request.create(status: "pending", jam_session: jamsession4, user: user5)
Request.create(status: "pending", jam_session: jamsession4, user: user6)
Request.create(status: "pending", jam_session: jamsession4, user: user7)
Request.create(status: "pending", jam_session: jamsession4, user: user8)
Request.create(status: "pending", jam_session: jamsession5, user: user1)
Request.create(status: "pending", jam_session: jamsession5, user: user4)
Request.create(status: "pending", jam_session: jamsession5, user: user5)
Request.create(status: "pending", jam_session: jamsession5, user: user6)
Request.create(status: "pending", jam_session: jamsession5, user: user7)
Request.create(status: "pending", jam_session: jamsession5, user: user8)
Request.create(status: "pending", jam_session: jamsession6, user: user1)
Request.create(status: "pending", jam_session: jamsession6, user: user4)
Request.create(status: "pending", jam_session: jamsession6, user: user5)
Request.create(status: "pending", jam_session: jamsession6, user: user6)
Request.create(status: "pending", jam_session: jamsession6, user: user7)
Request.create(status: "pending", jam_session: jamsession6, user: user7)
Request.create(status: "pending", jam_session: jamsession7, user: user1)
Request.create(status: "pending", jam_session: jamsession7, user: user4)
Request.create(status: "pending", jam_session: jamsession7, user: user5)
Request.create(status: "pending", jam_session: jamsession7, user: user6)
Request.create(status: "pending", jam_session: jamsession7, user: user7)
Request.create(status: "pending", jam_session: jamsession7, user: user8)
Request.create(status: "pending", jam_session: jamsession8, user: user1)
Request.create(status: "pending", jam_session: jamsession8, user: user4)
Request.create(status: "pending", jam_session: jamsession8, user: user5)
Request.create(status: "pending", jam_session: jamsession8, user: user6)
Request.create(status: "pending", jam_session: jamsession8, user: user7)
Request.create(status: "pending", jam_session: jamsession8, user: user8)
Request.create(status: "pending", jam_session: jamsession9, user: user1)
Request.create(status: "pending", jam_session: jamsession9, user: user2)
Request.create(status: "pending", jam_session: jamsession9, user: user5)
Request.create(status: "pending", jam_session: jamsession9, user: user6)
Request.create(status: "pending", jam_session: jamsession9, user: user7)
Request.create(status: "pending", jam_session: jamsession9, user: user8)
Request.create(status: "pending", jam_session: jamsession10, user: user1)
Request.create(status: "pending", jam_session: jamsession10, user: user2)
Request.create(status: "pending", jam_session: jamsession10, user: user5)
Request.create(status: "pending", jam_session: jamsession10, user: user6)
Request.create(status: "pending", jam_session: jamsession10, user: user7)
Request.create(status: "pending", jam_session: jamsession10, user: user7)
Request.create(status: "pending", jam_session: jamsession11, user: user1)
Request.create(status: "pending", jam_session: jamsession11, user: user2)
Request.create(status: "pending", jam_session: jamsession11, user: user5)
Request.create(status: "pending", jam_session: jamsession11, user: user6)
Request.create(status: "pending", jam_session: jamsession11, user: user7)
Request.create(status: "pending", jam_session: jamsession11, user: user8)
Request.create(status: "pending", jam_session: jamsession12, user: user1)
Request.create(status: "pending", jam_session: jamsession12, user: user2)
Request.create(status: "pending", jam_session: jamsession12, user: user5)
Request.create(status: "pending", jam_session: jamsession12, user: user6)
Request.create(status: "pending", jam_session: jamsession12, user: user7)
Request.create(status: "pending", jam_session: jamsession12, user: user8)
Request.create(status: "pending", jam_session: jamsession13, user: user1)
Request.create(status: "pending", jam_session: jamsession13, user: user2)
Request.create(status: "pending", jam_session: jamsession13, user: user4)
Request.create(status: "pending", jam_session: jamsession13, user: user6)
Request.create(status: "pending", jam_session: jamsession13, user: user7)
Request.create(status: "pending", jam_session: jamsession13, user: user8)
Request.create(status: "pending", jam_session: jamsession14, user: user1)
Request.create(status: "pending", jam_session: jamsession14, user: user2)
Request.create(status: "pending", jam_session: jamsession14, user: user4)
Request.create(status: "pending", jam_session: jamsession14, user: user6)
Request.create(status: "pending", jam_session: jamsession14, user: user7)
Request.create(status: "pending", jam_session: jamsession14, user: user7)
Request.create(status: "pending", jam_session: jamsession15, user: user1)
Request.create(status: "pending", jam_session: jamsession15, user: user2)
Request.create(status: "pending", jam_session: jamsession15, user: user4)
Request.create(status: "pending", jam_session: jamsession15, user: user6)
Request.create(status: "pending", jam_session: jamsession15, user: user7)
Request.create(status: "pending", jam_session: jamsession15, user: user8)
Request.create(status: "pending", jam_session: jamsession16, user: user1)
Request.create(status: "pending", jam_session: jamsession16, user: user2)
Request.create(status: "pending", jam_session: jamsession16, user: user4)
Request.create(status: "pending", jam_session: jamsession16, user: user6)
Request.create(status: "pending", jam_session: jamsession16, user: user7)
Request.create(status: "pending", jam_session: jamsession16, user: user8)
Request.create(status: "pending", jam_session: jamsession17, user: user1)
Request.create(status: "pending", jam_session: jamsession17, user: user2)
Request.create(status: "pending", jam_session: jamsession17, user: user4)
Request.create(status: "pending", jam_session: jamsession17, user: user5)
Request.create(status: "pending", jam_session: jamsession17, user: user7)
Request.create(status: "pending", jam_session: jamsession17, user: user8)
Request.create(status: "pending", jam_session: jamsession18, user: user1)
Request.create(status: "pending", jam_session: jamsession18, user: user2)
Request.create(status: "pending", jam_session: jamsession18, user: user4)
Request.create(status: "pending", jam_session: jamsession18, user: user5)
Request.create(status: "pending", jam_session: jamsession18, user: user7)
Request.create(status: "pending", jam_session: jamsession18, user: user7)
Request.create(status: "pending", jam_session: jamsession19, user: user1)
Request.create(status: "pending", jam_session: jamsession19, user: user2)
Request.create(status: "pending", jam_session: jamsession19, user: user4)
Request.create(status: "pending", jam_session: jamsession19, user: user5)
Request.create(status: "pending", jam_session: jamsession19, user: user7)
Request.create(status: "pending", jam_session: jamsession19, user: user8)
Request.create(status: "pending", jam_session: jamsession20, user: user1)
Request.create(status: "pending", jam_session: jamsession20, user: user2)
Request.create(status: "pending", jam_session: jamsession20, user: user4)
Request.create(status: "pending", jam_session: jamsession20, user: user5)
Request.create(status: "pending", jam_session: jamsession20, user: user7)
Request.create(status: "pending", jam_session: jamsession20, user: user8)
Request.create(status: "pending", jam_session: jamsession21, user: user1)
Request.create(status: "pending", jam_session: jamsession21, user: user2)
Request.create(status: "pending", jam_session: jamsession21, user: user4)
Request.create(status: "pending", jam_session: jamsession21, user: user5)
Request.create(status: "pending", jam_session: jamsession21, user: user7)
Request.create(status: "pending", jam_session: jamsession21, user: user6)
Request.create(status: "pending", jam_session: jamsession22, user: user1)
Request.create(status: "pending", jam_session: jamsession22, user: user2)
Request.create(status: "pending", jam_session: jamsession22, user: user4)
Request.create(status: "pending", jam_session: jamsession22, user: user5)
Request.create(status: "pending", jam_session: jamsession22, user: user7)
Request.create(status: "pending", jam_session: jamsession22, user: user7)
Request.create(status: "pending", jam_session: jamsession23, user: user1)
Request.create(status: "pending", jam_session: jamsession23, user: user2)
Request.create(status: "pending", jam_session: jamsession23, user: user4)
Request.create(status: "pending", jam_session: jamsession23, user: user5)
Request.create(status: "pending", jam_session: jamsession23, user: user7)
Request.create(status: "pending", jam_session: jamsession23, user: user6)
Request.create(status: "pending", jam_session: jamsession24, user: user1)
Request.create(status: "pending", jam_session: jamsession24, user: user2)
Request.create(status: "pending", jam_session: jamsession24, user: user4)
Request.create(status: "pending", jam_session: jamsession24, user: user5)
Request.create(status: "pending", jam_session: jamsession24, user: user7)
Request.create(status: "pending", jam_session: jamsession24, user: user6)
Request.create(status: "pending", jam_session: jamsession25, user: user1)
Request.create(status: "pending", jam_session: jamsession25, user: user2)
Request.create(status: "pending", jam_session: jamsession25, user: user4)
Request.create(status: "pending", jam_session: jamsession25, user: user5)
Request.create(status: "pending", jam_session: jamsession25, user: user7)
Request.create(status: "pending", jam_session: jamsession25, user: user6)

puts "Creating 8 posts per Jam Session"
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession1)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession2)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession3)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession4)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession5)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession6)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession7)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession8)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession9)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession10)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession11)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession12)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession13)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession14)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession15)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession16)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession17)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession18)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession19)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession20)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession21)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession22)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession23)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession24)
Post.create(content: "Oh wauw I really want to go to this amazing Jam Session!", user: user1, jam_session: jamsession25)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession1)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession2)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession3)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession4)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession5)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession6)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession7)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession8)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession9)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession10)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession11)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession12)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession13)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession14)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession15)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession16)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession17)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession18)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession19)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession20)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession21)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession22)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession23)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession24)
Post.create(content: "Yes me too, you wanna go together?", user: user2, jam_session: jamsession25)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession1)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession2)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession3)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession4)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession5)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession6)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession7)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession8)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession9)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession10)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession11)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession12)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession13)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession14)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession15)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession16)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession17)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession18)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession19)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession20)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession21)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession22)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession23)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession24)
Post.create(content: "Allriht I will pick you up around 21.00?", user: user1, jam_session: jamsession25)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession1)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession2)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession3)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession4)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession5)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession6)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession7)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession8)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession9)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession10)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession11)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession12)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession13)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession14)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession15)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession16)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession17)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession18)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession19)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession20)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession21)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession22)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession23)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession24)
Post.create(content: "I don't like music", user: user7, jam_session: jamsession25)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession1)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession2)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession3)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession4)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession5)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession6)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession7)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession8)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession9)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession10)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession11)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession12)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession13)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession14)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession15)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession16)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession17)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession18)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession19)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession20)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession21)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession22)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession23)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession24)
Post.create(content: "I will take my Flute", user: user8, jam_session: jamsession25)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession1)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession2)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession3)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession4)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession5)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession6)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession7)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession8)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession9)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession10)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession11)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession12)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession13)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession14)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession15)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession16)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession17)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession18)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession19)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession20)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession21)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession22)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession23)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession24)
Post.create(content: "Oeeeh Baracky can I play your flute ;-)", user: user4, jam_session: jamsession25)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession1)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession2)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession3)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession4)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession5)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession6)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession7)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession8)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession9)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession10)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession11)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession12)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession13)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession14)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession15)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession16)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession17)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession18)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession19)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession20)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession21)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession22)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession23)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession24)
Post.create(content: "No Angela not again, lol", user: user8, jam_session: jamsession25)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession1)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession2)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession3)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession4)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession5)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession6)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession7)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession8)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession9)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession10)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession11)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession12)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession13)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession14)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession15)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession16)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession17)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession18)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession19)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession20)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession21)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession22)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession23)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession24)
Post.create(content: "I will join as well! See you guys there!", user: user5, jam_session: jamsession25)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession1)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession2)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession3)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession4)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession5)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession6)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession7)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession8)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession9)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession10)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession11)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession12)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession13)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession14)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession15)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession16)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession17)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession18)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession19)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession20)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession21)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession22)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession23)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession24)
Post.create(content: "Aahh shit I can't make it, still stuck in NK", user: user6, jam_session: jamsession25)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession1)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession2)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession3)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession4)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession5)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession6)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession7)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession8)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession9)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession10)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession11)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession12)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession13)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession14)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession15)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession16)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession17)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession18)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession19)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession20)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession21)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession22)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession23)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession24)
Post.create(content: "Bonjour je ne peux pas venir, j'ai une présentation pour Le Wagon.", user: user3, jam_session: jamsession25)
